# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160610_0056'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='_tagulous_post_tags',
            managers=[
            ],
        ),
    ]
